[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "GiftLogic.lua"
pattern = "local giftData = GiftData[name]"
position = "before"
payload = '''
if name == "ArtemisUpgrade" then
    name = "NPC_Artemis_01"
elseif name == "DionysusUpgrade" then
    name = "NPC_Dionysus_01"
elseif name == "AthenaUpgrade" then
    name = "NPC_Athena_01"
end
'''
match_indent = true
times = 1
